development: &non_production_settings
    google_key: "ABQIAAAAUzkItq4p7LYo2YIR_gtjpRTJQa0g3IQ9GZqIMmInSLzwtGDKaBSzEc8_FNxIfQLkpKOh9R4JB87Rig" 

test:
    <<: *non_production_settings

staging:
    google_key: KeyForStagingDomainGoesHere

stable:
    google_key: KeyForStableDomainGoesHere